{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aggregator
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aggregator
subjects:
- kind: ServiceAccount
  name: aggregator
  namespace: {{ .Values.namespace }}
{{- end -}}